# 파일 규격 버전
version: "3"

services: 
  development:
    image: jhlee5391/python-rest-api:devlopment
    build:
      context: .
    ports:
        - "80:80"
  versioning:
    image: jhlee5391/python-rest-api:${BUILD_VERSION:-0.0.0}
    build:
      context: .
    ports:
        - "80:80"