# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create .env file
      run: |
        echo "database_hostname="127.0.0.1"" >> .env
        echo "database_port=3306" >> .env
        echo "database_password="1234"" >> .env
        echo "database_name="python_rest_api"" >> .env
        echo "database_username="root"" >> .env
        echo "secret_key="test"" >> .env
        echo "algorithm="HS256"" >> .env
        echo "access_token_expire_minutes=30" >> .env
        cat .env
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        echo "MAJOR : ${{ secrets.MAJOR }}, MINOR : ${{ secrets.MINOR }}"
